name = "cf-ai-assistant"
main = "src/index.js"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "CHAT_MEMORY"
class_name = "ChatMemory"

[[workflows]]
binding = "CHAT_WORKFLOW"
class_name = "ChatWorkflow"
script_name = "cf-ai-assistant"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatMemory"]

[env.production]
name = "cf-ai-assistant-prod"

[env.staging]
name = "cf-ai-assistant-staging"